[pytest]

# Diretório padrão de testes
testpaths = tests

# Mostrar detalhes úteis
addopts = 
    -vv
    -s
    --strict-markers
    --disable-warnings

# Marcação de categorias
markers =
    e2e: Testes ponta a ponta com backend real
    smoke: Testes rápidos de sanidade
    performance: Testes de tempo de resposta
    analytics: Testes de métricas territoriais
    surface: Testes de geração de superfície espacial

timeout = 60
