"""add municipalities and risk_surfaces

Revision ID: 70865ee17315
Revises: f9e058cd3bad
Create Date: 2026-02-18 13:27:01.439239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '70865ee17315'
down_revision: Union[str, Sequence[str], None] = 'f9e058cd3bad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('municipalities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('ibge_code', sa.String(length=10), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('geojson', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('bbox_min_lat', sa.Float(), nullable=False),
    sa.Column('bbox_min_lon', sa.Float(), nullable=False),
    sa.Column('bbox_max_lat', sa.Float(), nullable=False),
    sa.Column('bbox_max_lon', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('idx_municipality_active', 'municipalities', ['active'], unique=False)
    op.create_index(op.f('ix_municipalities_ibge_code'), 'municipalities', ['ibge_code'], unique=False)
    op.create_table('risk_surfaces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('municipality_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('geojson', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('grid_resolution_m', sa.Integer(), nullable=False),
    sa.Column('kernel_sigma_m', sa.Integer(), nullable=False),
    sa.Column('total_cells', sa.Integer(), nullable=True),
    sa.Column('total_area_m2', sa.Float(), nullable=True),
    sa.Column('high_risk_area_m2', sa.Float(), nullable=True),
    sa.Column('high_risk_percentage', sa.Float(), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['municipality_id'], ['municipalities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('municipality_id', 'snapshot_timestamp', name='uq_municipality_surface_timestamp')
    )
    op.create_index('idx_municipality_surface_timestamp', 'risk_surfaces', ['municipality_id', 'snapshot_timestamp'], unique=False)
    op.create_index(op.f('ix_risk_surfaces_municipality_id'), 'risk_surfaces', ['municipality_id'], unique=False)
    op.create_index(op.f('ix_risk_surfaces_snapshot_timestamp'), 'risk_surfaces', ['snapshot_timestamp'], unique=False)
    op.add_column('points', sa.Column('municipality_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_points_municipality_id'), 'points', ['municipality_id'], unique=False)
    op.create_foreign_key('fk_points_municipality_id', 'points', 'municipalities', ['municipality_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_points_municipality_id', 'points', type_='foreignkey')
    op.drop_index(op.f('ix_points_municipality_id'), table_name='points')
    op.drop_column('points', 'municipality_id')
    op.drop_index(op.f('ix_risk_surfaces_snapshot_timestamp'), table_name='risk_surfaces')
    op.drop_index(op.f('ix_risk_surfaces_municipality_id'), table_name='risk_surfaces')
    op.drop_index('idx_municipality_surface_timestamp', table_name='risk_surfaces')
    op.drop_table('risk_surfaces')
    op.drop_index(op.f('ix_municipalities_ibge_code'), table_name='municipalities')
    op.drop_index('idx_municipality_active', table_name='municipalities')
    op.drop_table('municipalities')
    # ### end Alembic commands ###
