"""initial clean schema

Revision ID: f9e058cd3bad
Revises: 
Create Date: 2026-02-16 21:16:54.124861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9e058cd3bad'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('points',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('influence_radius_m', sa.Integer(), nullable=False),
    sa.Column('neighborhood', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('risk_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('point_id', sa.String(length=64), nullable=False),
    sa.Column('snapshot_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('icra', sa.Float(), nullable=False),
    sa.Column('icra_std', sa.Float(), nullable=True),
    sa.Column('nivel_risco', sa.String(length=50), nullable=False),
    sa.Column('confianca', sa.String(length=50), nullable=True),
    sa.Column('chuva_dia', sa.Float(), nullable=True),
    sa.Column('chuva_30d', sa.Float(), nullable=True),
    sa.Column('chuva_90d', sa.Float(), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['point_id'], ['points.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('point_id', 'snapshot_timestamp', name='uq_point_snapshot_timestamp')
    )
    op.create_index('idx_point_snapshot_timestamp', 'risk_snapshots', ['point_id', 'snapshot_timestamp'], unique=False)
    op.create_index(op.f('ix_risk_snapshots_point_id'), 'risk_snapshots', ['point_id'], unique=False)
    op.create_index(op.f('ix_risk_snapshots_snapshot_timestamp'), 'risk_snapshots', ['snapshot_timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_risk_snapshots_snapshot_timestamp'), table_name='risk_snapshots')
    op.drop_index(op.f('ix_risk_snapshots_point_id'), table_name='risk_snapshots')
    op.drop_index('idx_point_snapshot_timestamp', table_name='risk_snapshots')
    op.drop_table('risk_snapshots')
    op.drop_table('points')
    # ### end Alembic commands ###
